### ISSUE TITLE
Error: Running LUA method 'update'.

### ISSUE THREAD

**Issue by regs1980** [Peppie84/FS22_ExtendedGameInfoDisplay#10]
Starte ich das Spiel mit aktivierter Temperatur per Einstellung, kommt dieser lua Fehler.

Error: Running LUA method 'update'.
dataS/scripts/environment/weather/Weather.lua(718) : attempt to index local 'instance' (a nil value)

aktivierter Temperatur

[log Temp on.txt](https://github.com/Peppie84/FS22_ExtendedGameInfoDisplay/files/11578897/log.Temp.on.txt)

Deaktiviere ich es aber und starte dann das Spiel, schreibt sich keiner in die log.

Deaktivierter Temperatur

[log temp off.txt](https://github.com/Peppie84/FS22_ExtendedGameInfoDisplay/files/11578906/log.temp.off.txt)

**Comment by Peppie84** [comment]
Danke @regs1980 , ich prüfe es.

**Comment by Peppie84** [comment]
@regs1980 ich kann den Fehler auf einer Giants-Karte nicht reproduzieren. Vielleicht schlägt eine andere Mod dazwischen oder eine Karte. Ich bräucht noch ein paar Infos:

- Welche Karte spielst du?
- Hast du das Problem auch, wenn du ein neues Spiel startest wo nur diese Mod aktiv ist, mit einer Giants-Karte?
- Wenn möglich, kannst du mir eine Liste an Mods zukommen lassen, die du bei diesem Save benutzt

danke

**Comment by regs1980** [comment]
Ich habe es jetzt mal durchgetestet, es tritt nur im Multiplayer auf, egal bei welcher Karte. 

Standardkarte Elmcreek

[log.txt](https://github.com/Peppie84/FS22_ExtendedGameInfoDisplay/files/11579753/log.txt)

**Comment by Peppie84** [comment]
@regs1980 vielen Dank für die Hilfe. Als du Multiplayer sagtest, dann kam es mir schon. Im Loading / Jetzt Starten-Screen wird im Hintergrund schon die Temperatur-Daten ausgelesen aber es dauert etwas bis der Server die Forecast.xml Daten an den Client gesendet hat. Solange die Daten nicht vorhanden sind kommt dieser Fehler.

Ich habe jetzt ein fix eingebaut wo das auslesen der Temperatur-Daten später stattfindet.

**Comment by Peppie84** [comment]
Da es etwas dauern kann bis ich das nächste Release mache, könnt ihr hier die Version mit dem Fix downloaden, wer mag.
Der Fehler hindert nicht am spielen, wird nur jeweils beim verbinden auf einen Dedi-Server beim Client in der Log geworfen.

[FS22_ExtendedGameInfoDisplay-dev.zip](https://github.com/Peppie84/FS22_ExtendedGameInfoDisplay/files/11579979/FS22_ExtendedGameInfoDisplay-dev.zip)
