### ISSUE TITLE
Only reports celsius - needs Fahrenheit when the user has it set that way

### ISSUE THREAD

**Issue by sjmills** [Peppie84/FS22_ExtendedGameInfoDisplay#12]
Title says it all.

**Comment by Peppie84** [comment]
Hi @sjmills , thanks for your report. I will now display Fahrenheit if it's enabled.

![image](https://github.com/Peppie84/FS22_ExtendedGameInfoDisplay/assets/7722222/4edf78d7-34df-4ca0-95e2-d55e2583145d)
