### ISSUE TITLE
Jahreswechsel

### ISSUE THREAD

**Issue by Benjisgaming** [Peppie84/FS22_ExtendedGameInfoDisplay#17]
Moin ich hab ma eine Frage ich war im Dezember in Jahr 2. passt alles soweit, jetzt bin ich im Januar und immer noch in Jahr 2. wechselt der erst im August in Jahr 3??? 
wenn ja wäre es toll wenn man das ändern könnte vielen dank.

**Comment by Peppie84** [comment]
Moin @Benjisgaming , bei Giants startet das Jahr im März. Im Code ist der Monat Januar die Zahl 11 und der Monat Februar= 12. Das wird was größeres das umzuprogrammieren. Ich glaube die Mod: https://www.farming-simulator.com/mod.php?mod_id=257991 ändert auch die Rechnung des Jahres.

Edit: Die Mod scheint nur bei neuen Saves zu funktionieren. Falls du das dennoch testen magst, mach bitte ein Backup vorher :sweat_smile:

Ich lass das Ticket hier mal offen zum Vote.

**Comment by Peppie84** [comment]
Ich denke, dass ich den Jahreswechsel hier in diese Mod nicht mit aufnehmen werden. Ich möchte gerne das diese Mod nur eine Anzeige-Mod bleibt, ohne auf das Gameplay einzuwirken. Man könnte überlegen dies in einer eigenen kleinen Mod dazustellen.

- Man müsste bei `onMonthChange` dann prüfen ob es Jan ist
- Wenn ja, dann `onYearChange` triggern
- Die Jahr/Monat und Tag Berechnung aufgrund der `currentDay`-Variable muss angepasst werden

Wenn ich Zeit dafür finde, dann werde ich das machen, aber dieses Ticket werde ich schließen da es nichts mit der Mod zu tun hat.
