### ISSUE TITLE
temperature translations

### ISSUE THREAD

**Issue by dylan13tx** [Peppie84/FS22_ExtendedGameInfoDisplay#18]
loving the mod except when playing on US based maps that use GIANTS mapUS enviroment.xml only show the temperature in Celsius and not Fahrenheit. for example I'm playing on Spring Creek, ND and it shows the temperature in Celsius when in the game menu it shows it in Fahrenheit. In the next update can you add the ability for the mod to show temperatures in Fahrenheit when the map is running with GIANTS mapUS enviroment.xml? I made sure the game setting was set at Fahrenheit and in the the middle of the summer its shows the Celsius temperatures and never in Fahrenheit. Other than that no issues for me. Thank you.

**Comment by Peppie84** [comment]
Hi @dylan13tx , thanks. On the next release (#12) this mod can also display Fahrenheit if it's enabled via the settings. This feature is also already pushed into the development branch. So you can download the source and use it right now. The next release will maybe in two/three weeks.

**Comment by dylan13tx** [comment]
do I turn on Fahrenheit? i have it turned on in the base game settings but I don't see any setting for Fahrenheit for the mod. i downloaded the most recent version from the Modhub.

**Comment by Peppie84** [comment]
No, it's on the next/upcoming release for modhub. But currently here on github when you download the source-code. Here is the current development version:
[FS22_ExtendedGameInfoDisplay-dev.zip](https://github.com/Peppie84/FS22_ExtendedGameInfoDisplay/files/11632000/FS22_ExtendedGameInfoDisplay-dev.zip)

**Comment by dylan13tx** [comment]
I downloaded the zip file you sent but it won’t show up in game. It’s like
the game doesn’t read it. The modhub version shows up though.

**Comment by Peppie84** [comment]
You have to rename the *.zip and remove the `-dev` from the name. - sorry, it was the suffix for the development branch version. Then overwrite the FS22_ExtendedGameInfoDisplay.zip on your mod-folder with the downloaded and renamed one.

Edit: and activate the Fahrenheit on your settings if not already set.

**Comment by dylan13tx** [comment]
Got it to work thank you. Definitely going to enjoy the mod even more!

**Comment by Peppie84** [comment]
thanks 😀
