### ISSUE TITLE
Improvement - Add unit selection. 

### ISSUE THREAD

**Issue by talianagisan** [Peppie84/FS22_ExtendedGameInfoDisplay#19]
If we had a SETTING to show F or C that would be nice. Right now it's permanently in C and as someone from the land of cheeseburgers celcius means as much to me as healthy eating.

**Comment by Peppie84** [comment]
Hi @talianagisan from the land of cheeseburgers, currently i'm waiting for the next release. I've submitted the next version V1.2.0.0 with the changelog:

## [1.2.0.0] - #waiting-for-modhub#
- Added `l10n_hu.xml` by [ZsPetrovics](https://github.com/ZsPetrovics)
- Fixed lua error while connecting to dedi-server - for [#10](https://github.com/Peppie84/FS22_ExtendedGameInfoDisplay/issues/10)
- Display temperatur also in Fahrenheit if set via settings - for [#12](https://github.com/Peppie84/FS22_ExtendedGameInfoDisplay/issues/12)
- Added `l10n_ru.xml` by [vitalii2011](https://github.com/vitalii2011)
- modDesc.xml descVersion update

Does the third point fulfill your ticket?

**Comment by talianagisan** [comment]
> Hi @talianagisan from the land of cheeseburgers, currently i'm waiting for the next release. I've submitted the next version V1.2.0.0 with the changelog:
> 
> ## [1.2.0.0] - #waiting-for-modhub#
> * Added `l10n_hu.xml` by [ZsPetrovics](https://github.com/ZsPetrovics)
> * Fixed lua error while connecting to dedi-server - for [#10](https://github.com/Peppie84/FS22_ExtendedGameInfoDisplay/issues/10)
> * Display temperatur also in Fahrenheit if set via settings - for [#12](https://github.com/Peppie84/FS22_ExtendedGameInfoDisplay/issues/12)
> * Added `l10n_ru.xml` by [vitalii2011](https://github.com/vitalii2011)
> * modDesc.xml descVersion update
> 
> Does the third point fulfill your ticket?

Does it go based off the miles/kilometers setting ingame or is it a totally different option? If it is user selectable yes it does fufill, if it automatically adjusts based on miles/kilometers then no.

**Comment by Peppie84** [comment]
There is a base game option to choose which unit you want:
![image](https://github.com/Peppie84/FS22_ExtendedGameInfoDisplay/assets/7722222/45733fc2-861c-4af3-8717-e3484e3f3045)

**Comment by Peppie84** [comment]
This feature is implemented with #12 . I'll close this ticket.
