### ISSUE TITLE
Frage zum angezeigten Jahr

### ISSUE THREAD

**Issue by MeRida2104** [Peppie84/FS22_ExtendedGameInfoDisplay#22]
Hey, danke für deinen Mod. Ist bei uns im Projekt sehr hilfreich, vor allem durch die Anzeige des Ingame Jahres. Ich habe dazu allerdings eine Frage, ist also in dem Sinne kein Bug. Wir haben für unseren Projektstart von August in den März gespult. Dadurch ist es nun bereits Jahr 2 statt wie eigentlich vorgesehen Jahr 1.

Weißt du ob es eine Möglichkeit gibt das Jahr wieder "zu resetten", sodass wir März Jahr 1 haben? 

Beste Grüße

**Comment by Peppie84** [comment]
Hi @MeRida2104 ,

vielen Dank. Es gibt leider keine Möglichkeit das Jahr zu resetten. Was du aber machen kannst:
- Mal die Mod: https://www.farming-simulator.com/mod.php?mod_id=257991 testen ob das damit klappt 
- oder einfacher, nach Start eines neuen Spielstandes, einfach speichern und im Savegame-Folder die Datei: `environment.xml` öffnen. Dort gibt es einen Wert: `currentDay` und `currentMonotonicDay`. Bei einem neuen Save stehen beide Werte auf 6. Hier musst du die Werte nur auf 1 (1=März) ändern, abspeichern und das Spiel wieder starten.
```xml
    <currentDay>1</currentDay>
    <currentMonotonicDay>1</currentMonotonicDay>
```

grüße

**Comment by MeRida2104** [comment]
Moin @Peppie84 , 

startinSpring hatten wir getestet, aber es hat uns zu viel "drum herum" geändert. Bspw waren normale Felder plötzlich Wiesen oder bei manchen Feldern (die NPCs gehörten) lief beim Monatswechsel das Wachstum nicht weiter. 

Dein zweiter Tipp klingt interessant. Kann ich die Änderung auch im aktuellen Savegame machen? Wir sind noch im März.

**Comment by Peppie84** [comment]
Variante zwei sollte zu jedem Zeitpunkt möglich sein. Du solltest vielleicht trotzdem vorher noch ein Backup machen 😅 - Ich hoffe das es keine Seiteneffekte haben wird.

Viel Erfolg.
