### ISSUE TITLE
Contributing with Spanish Translation

### ISSUE THREAD

**Issue by Ferchu425** [Peppie84/FS22_ExtendedGameInfoDisplay#23]
Hi there, first at all thank you for the good work, I really like simple mods like this, and yours is one I do like a lot so, if you want, Im sending you the spanish translation for you to add if possible, hope it's ok

[ln10n_es.txt](https://github.com/Peppie84/FS22_ExtendedGameInfoDisplay/files/15071865/ln10n_es.txt)

PD: This is not an "issue" but Im not good at "git", so this is the way that I found

**Comment by Peppie84** [comment]
Thanks @Ferchu425
